const sentences = [
    { title: 1, english: "John's Renaissance: A Story of Determination and Triumph", 
        bulgarian: "Ренесансът на Джон: История на решителност и триумф", 
        audioEn: "audio/C2/0001_ENG.mp3", 
        audioBg: "audio/C2/0001_BUL.mp3" },
    { english: 'John was born into a life of poverty in a small English village, where opportunities were scarce.', 
        bulgarian: 'Джон се роди в бедно семейство в малко английско селце, където възможностите бяха оскъдни.', 
        audioEn: "audio/C2/0002_ENG.mp3", 
        audioBg: "audio/C2/0002_BUL.mp3" },
    { english: 'Despite the hardships, John exhibited an extraordinary intellect and an insatiable thirst for knowledge from a young age.', 
        bulgarian: 'Въпреки трудностите, Джон проявяваше изключителен интелект и ненаситна жажда за знания още от малък.', 
        audioEn: "audio/C2/0003_ENG.mp3", 
        audioBg: "audio/C2/0003_BUL.mp3" },
    { english: 'Determined to break free from the shackles of poverty, he moved to the city at 16, seeking a brighter future.', 
        bulgarian: 'Решен да се освободи от оковите на бедността, той се премести в града на 16-годишна възраст, търсейки по-светло бъдеще.', 
        audioEn: "audio/C2/0004_ENG.mp3", 
        audioBg: "audio/C2/0004_BUL.mp3" },
    { english: 'John found employment in a printing shop, where he toiled by day and studied by night, honing his skills and expanding his knowledge.', 
        bulgarian: 'Джон намери работа в печатница, където се труди през деня и учеше през нощта, усъвършенствайки уменията си и разширявайки знанията си.', 
        audioEn: "audio/C2/0005_ENG.mp3", 
        audioBg: "audio/C2/0005_BUL.mp3" },
    { english: 'His relentless dedication and perseverance eventually paid off when he saved enough to open a school for underprivileged children.', 
        bulgarian: 'Неговата неуморна отдаденост и упоритост в крайна сметка се отплатиха, когато той спести достатъчно, за да отвори училище за бедни деца.', 
        audioEn: "audio/C2/0006_ENG.mp3", 
        audioBg: "audio/C2/0006_BUL.mp3" },
    { english: 'The school, initially modest, quickly grew in reputation due to John\'s innovative teaching methods and unwavering commitment.', 
        bulgarian: 'Училището, първоначално скромно, бързо придоби репутация благодарение на иновативните методи на преподаване на Джон и непоколебимата му отдаденост.', 
        audioEn: "audio/C2/0007_ENG.mp3", 
        audioBg: "audio/C2/0007_BUL.mp3" },
    { english: 'Despite facing significant resistance from traditionalists who opposed his progressive ideas, John stood firm in his mission to provide quality education for all.', 
        bulgarian: 'Въпреки че се сблъскваше със значителна съпротива от страна на традиционалисти, които се противопоставяха на неговите прогресивни идеи, Джон остана твърд в мисията си да осигури качествено образование за всички.', 
        audioEn: "audio/C2/0008_ENG.mp3", 
        audioBg: "audio/C2/0008_BUL.mp3" },
    { english: 'A generous donation from a local philanthropist enabled the school to expand, offering better facilities and more opportunities for its students.', 
        bulgarian: 'Щедро дарение от местен филантроп позволи разширяването на училището, предлагайки по-добри съоръжения и повече възможности за учениците.', 
        audioEn: "audio/C2/0009_ENG.mp3", 
        audioBg: "audio/C2/0009_BUL.mp3" },
    { english: 'John\'s school became a beacon of hope, inspiring many of its students to achieve exceptional success in various fields.', 
        bulgarian: 'Училището на Джон се превърна в маяк на надежда, вдъхновявайки много от учениците си да постигнат изключителен успех в различни области.', 
        audioEn: "audio/C2/0010_ENG.mp3", 
        audioBg: "audio/C2/0010_BUL.mp3" }
];

