const sentences = [
    { title:1, english: "John's Renaissance", 
        bulgarian: "Ренесансът на Джон", 
        audioEn: "audio/ORIG/0001_ENG.mp3", 
        audioBg: "audio/ORIG/0001_BUL.mp3" },
    { english: 'John grew up in a small English village where poverty was a common occurrence.', 
        bulgarian: 'Джон израсна в малко английско селце, където бедността беше често срещано явление.', 
        audioEn: "audio/ORIG/0002_ENG.mp3", 
        audioBg: "audio/ORIG/0002_BUL.mp3" },
    { english: 'From a young age, he showed remarkable intelligence and a thirst for knowledge.', 
        bulgarian: 'Още от малък той показваше изключителна интелигентност и жажда за знания.', 
        audioEn: "audio/ORIG/0003_ENG.mp3", 
        audioBg: "audio/ORIG/0003_BUL.mp3" },
    { english: 'He studied diligently despite the lack of resources and support from his parents, who struggled to make ends meet.', 
        bulgarian: 'Той учеше усилено, въпреки липсата на ресурси и подкрепа от страна на родителите си, които едва свързваха двата края.', 
        audioEn: "audio/ORIG/0004_ENG.mp3", 
        audioBg: "audio/ORIG/0004_BUL.mp3" },
    { english: 'At the age of 16, John decided to leave his hometown in search of a better life in the big city.', 
        bulgarian: 'На 16 години, Джон реши да напусне родния си дом и да потърси по-добър живот в големия град.', 
        audioEn: "audio/ORIG/0005_ENG.mp3", 
        audioBg: "audio/ORIG/0005_BUL.mp3" },
    { english: 'He began working as an apprentice at a printing press, where he spent long hours learning and perfecting his craft.', 
        bulgarian: 'Той започна работа като чирак в печатница, където прекарваше дълги часове в учене и усъвършенстване на занаята си.', 
        audioEn: "audio/ORIG/0006_ENG.mp3", 
        audioBg: "audio/ORIG/0006_BUL.mp3" },
    { english: 'Despite the hardships and injustices he faced, John managed to earn the respect of his employer and received the opportunity to study at a local college.', 
        bulgarian: 'Въпреки трудностите и несправедливостите, с които се сблъскваше, Джон успя да спечели уважението на своя работодател и получи възможност да се обучава в местен колеж.', 
        audioEn: "audio/ORIG/0007_ENG.mp3", 
        audioBg: "audio/ORIG/0007_BUL.mp3" },
    { english: 'John studied various disciplines and discovered his passion for history and education.', 
        bulgarian: 'Джон изучаваше различни дисциплини и откри своята страст към историята и образованието.', 
        audioEn: "audio/ORIG/0008_ENG.mp3", 
        audioBg: "audio/ORIG/0008_BUL.mp3" },
    { english: 'Over time, he decided to dedicate his life to creating a school for poor children who had no access to education.', 
        bulgarian: 'С течение на времето той реши да посвети живота си на създаването на училище за бедни деца, които нямат достъп до образование.', 
        audioEn: "audio/ORIG/0009_ENG.mp3", 
        audioBg: "audio/ORIG/0009_BUL.mp3" },
    { english: 'Despite numerous obstacles, including lack of funding and resistance from local authorities, John managed to open his first school.', 
        bulgarian: 'Въпреки многобройните препятствия, включително липса на финансиране и съпротива от местните власти, Джон успя да отвори първото си училище.', 
        audioEn: "audio/ORIG/0010_ENG.mp3", 
        audioBg: "audio/ORIG/0010_BUL.mp3" },
    { english: 'The school started small, with just a handful of students, but John\'s dedication and innovative teaching methods quickly drew attention.', 
        bulgarian: 'Училището започна малко, само с няколко ученици, но отдадеността на Джон и неговите иновативни методи на преподаване бързо привлякоха внимание.', 
        audioEn: "audio/ORIG/0011_ENG.mp3", 
        audioBg: "audio/ORIG/0011_BUL.mp3" },
    { english: 'He introduced practical lessons and encouraged critical thinking, which was revolutionary at the time.', 
        bulgarian: 'Той въведе практически уроци и насърчаваше критичното мислене, което беше революционно за времето си.', 
        audioEn: "audio/ORIG/0012_ENG.mp3", 
        audioBg: "audio/ORIG/0012_BUL.mp3" },
    { english: 'As the school grew, John faced backlash from traditionalists who believed that education should remain a privilege for the wealthy.', 
        bulgarian: 'С разрастването на училището, Джон се сблъска с критика от традиционалисти, които вярваха, че образованието трябва да остане привилегия за богатите.', 
        audioEn: "audio/ORIG/0013_ENG.mp3", 
        audioBg: "audio/ORIG/0013_BUL.mp3" },
    { english: 'Undeterred, he continued to fight for his vision, often working late into the night to secure funding and resources.', 
        bulgarian: 'Без да се обезсърчава, той продължи да се бори за своята визия, често работейки до късно през нощта, за да осигури финансиране и ресурси.', 
        audioEn: "audio/ORIG/0014_ENG.mp3", 
        audioBg: "audio/ORIG/0014_BUL.mp3" },
    { english: 'John’s determination paid off when a local philanthropist, impressed by his dedication, donated a substantial sum to the school.', 
        bulgarian: 'Решителността на Джон се отплати, когато местен филантроп, впечатлен от неговата отдаденост, дари значителна сума на училището.', 
        audioEn: "audio/ORIG/0015_ENG.mp3", 
        audioBg: "audio/ORIG/0015_BUL.mp3" },
    { english: 'With this new funding, John was able to expand the school, hire more teachers, and provide better materials for the students.', 
        bulgarian: 'С това ново финансиране, Джон успя да разшири училището, да наеме повече учители и да осигури по-добри материали за учениците.', 
        audioEn: "audio/ORIG/0016_ENG.mp3", 
        audioBg: "audio/ORIG/0016_BUL.mp3" },
    { english: 'The school became a beacon of hope for many poor families in the area, offering their children a chance at a better future.', 
        bulgarian: 'Училището стана маяк на надежда за много бедни семейства в района, предлагайки на техните деца шанс за по-добро бъдеще.', 
        audioEn: "audio/ORIG/0017_ENG.mp3", 
        audioBg: "audio/ORIG/0017_BUL.mp3" },
    { english: 'John’s success continued to grow, and he was invited to speak at educational conferences across the country.', 
        bulgarian: 'Успехът на Джон продължаваше да расте и той беше поканен да говори на образователни конференции из цялата страна.', 
        audioEn: "audio/ORIG/0018_ENG.mp3", 
        audioBg: "audio/ORIG/0018_BUL.mp3" },
    { english: 'He used these opportunities to advocate for educational reform and to share his innovative methods with other educators.', 
        bulgarian: 'Той използваше тези възможности, за да се застъпва за образователни реформи и да споделя своите иновативни методи с други преподаватели.', 
        audioEn: "audio/ORIG/0019_ENG.mp3", 
        audioBg: "audio/ORIG/0019_BUL.mp3" },
    { english: 'Despite his growing fame, John remained humble and focused on his mission to provide education for all.', 
        bulgarian: 'Въпреки нарастващата си слава, Джон остана скромен и фокусиран върху мисията си да осигури образование за всички.', 
        audioEn: "audio/ORIG/0020_ENG.mp3", 
        audioBg: "audio/ORIG/0020_BUL.mp3" },
    { english: 'He continued to work closely with his students, always encouraging them to think critically and to strive for excellence.', 
        bulgarian: 'Той продължи да работи в тясно сътрудничество със своите ученици, винаги насърчавайки ги да мислят критично и да се стремят към съвършенство.', 
        audioEn: "audio/ORIG/0021_ENG.mp3", 
        audioBg: "audio/ORIG/0021_BUL.mp3" },
    { english: 'Over the years, many of John’s students went on to achieve great success in various fields, attributing their accomplishments to the solid foundation they received at his school.', 
        bulgarian: 'През годините много от учениците на Джон постигнаха големи успехи в различни области, приписвайки постиженията си на солидната основа, която получиха в неговото училище.', 
        audioEn: "audio/ORIG/0022_ENG.mp3", 
        audioBg: "audio/ORIG/0022_BUL.mp3" },
    { english: 'John’s life was not without personal sacrifices; he never married or had children of his own, dedicating all his time and resources to his school.', 
        bulgarian: 'Животът на Джон не мина без лични жертви; той никога не се ожени и нямаше собствени деца, посвещавайки цялото си време и ресурси на своето училище.', 
        audioEn: "audio/ORIG/0023_ENG.mp3", 
        audioBg: "audio/ORIG/0023_BUL.mp3" },
    { english: 'He lived modestly, pouring all his earnings back into the school to ensure its continued success.', 
        bulgarian: 'Той живееше скромно, инвестирайки всичките си приходи обратно в училището, за да осигури неговия продължаващ успех.', 
        audioEn: "audio/ORIG/0024_ENG.mp3", 
        audioBg: "audio/ORIG/0024_BUL.mp3" },
    { english: 'One of the greatest challenges John faced was when a fire broke out in the school, destroying much of the building and its resources.', 
        bulgarian: 'Едно от най-големите предизвикателства, пред които се изправи Джон, беше, когато избухна пожар в училището, унищожавайки голяма част от сградата и ресурсите.', 
        audioEn: "audio/ORIG/0025_ENG.mp3", 
        audioBg: "audio/ORIG/0025_BUL.mp3" },
    { english: 'The community was devastated, but John’s spirit remained unbroken.', 
        bulgarian: 'Общността беше опустошена, но духът на Джон остана непоколебим.', 
        audioEn: "audio/ORIG/0026_ENG.mp3", 
        audioBg: "audio/ORIG/0026_BUL.mp3" },
    { english: 'He organized a fundraising campaign and personally led the reconstruction efforts.', 
        bulgarian: 'Той организира кампания за събиране на средства и лично ръководи усилията за възстановяване.', 
        audioEn: "audio/ORIG/0027_ENG.mp3", 
        audioBg: "audio/ORIG/0027_BUL.mp3" },
    { english: 'His determination inspired many, and donations poured in from all over the country.', 
        bulgarian: 'Неговата решителност вдъхнови много хора и даренията потекоха от цялата страна.', 
        audioEn: "audio/ORIG/0028_ENG.mp3", 
        audioBg: "audio/ORIG/0028_BUL.mp3" },
    { english: 'Within a year, the school was rebuilt, bigger and better than before.', 
        bulgarian: 'В рамките на една година училището беше възстановено, по-голямо и по-добро от преди.', 
        audioEn: "audio/ORIG/0029_ENG.mp3", 
        audioBg: "audio/ORIG/0029_BUL.mp3" },
    { english: 'John’s unwavering commitment to education earned him numerous awards and recognition.', 
        bulgarian: 'Непоколебимата отдаденост на Джон към образованието му спечели многобройни награди и признания.', 
        audioEn: "audio/ORIG/0030_ENG.mp3", 
        audioBg: "audio/ORIG/0030_BUL.mp3" },
    { english: 'He was honored by the Queen and received an honorary doctorate from the university he once attended.', 
        bulgarian: 'Той беше почетен от кралицата и получи почетна докторска степен от университета, който някога посещаваше.', 
        audioEn: "audio/ORIG/0031_ENG.mp3", 
        audioBg: "audio/ORIG/0031_BUL.mp3" },
    { english: 'Despite these accolades, John remained focused on his mission.', 
        bulgarian: 'Въпреки тези отличия, Джон остана фокусиран върху своята мисия.', 
        audioEn: "audio/ORIG/0032_ENG.mp3", 
        audioBg: "audio/ORIG/0032_BUL.mp3" },
    { english: 'He continued to advocate for educational reform and worked tirelessly to improve the lives of his students.', 
        bulgarian: 'Той продължи да се застъпва за образователни реформи и работеше неуморно, за да подобри живота на своите ученици.', 
        audioEn: "audio/ORIG/0033_ENG.mp3", 
        audioBg: "audio/ORIG/0033_BUL.mp3" },
    { english: 'In his later years, John wrote a book about his experiences, sharing his journey and the lessons he learned along the way.', 
        bulgarian: 'В по-късните си години Джон написа книга за своите преживявания, споделяйки своето пътуване и уроците, които научи по пътя.', 
        audioEn: "audio/ORIG/0034_ENG.mp3", 
        audioBg: "audio/ORIG/0034_BUL.mp3" },
    { english: 'The book became a bestseller, inspiring countless individuals to pursue their dreams and make a difference in their communities.', 
        bulgarian: 'Книгата стана бестселър, вдъхновявайки безброй хора да преследват мечтите си и да направят промяна в своите общности.', 
        audioEn: "audio/ORIG/0035_ENG.mp3", 
        audioBg: "audio/ORIG/0035_BUL.mp3" },
    { english: 'John’s legacy lived on through the many lives he touched.', 
        bulgarian: 'Наследството на Джон продължи да живее чрез многото животи, които докосна.', 
        audioEn: "audio/ORIG/0036_ENG.mp3", 
        audioBg: "audio/ORIG/0036_BUL.mp3" },
    { english: 'His school continued to thrive, producing leaders, innovators, and changemakers.', 
        bulgarian: 'Неговото училище продължаваше да процъфтява, произвеждайки лидери, иноватори и носители на промяна.', 
        audioEn: "audio/ORIG/0037_ENG.mp3", 
        audioBg: "audio/ORIG/0037_BUL.mp3" },
    { english: 'John passed away peacefully at the age of 85, surrounded by former students who had become like family to him.', 
        bulgarian: 'Джон почина спокойно на 85-годишна възраст, заобиколен от бивши ученици, които му бяха станали като семейство.', 
        audioEn: "audio/ORIG/0038_ENG.mp3", 
        audioBg: "audio/ORIG/0038_BUL.mp3" },
    { english: 'His death was mourned by many, but his impact on the world would never be forgotten.', 
        bulgarian: 'Смъртта му беше оплаквана от мнозина, но неговото влияние върху света никога нямаше да бъде забравено.', 
        audioEn: "audio/ORIG/0039_ENG.mp3", 
        audioBg: "audio/ORIG/0039_BUL.mp3" },
    { english: 'John’s story is a testament to the power of education, determination, and the human spirit.', 
        bulgarian: 'Историята на Джон е свидетелство за силата на образованието, решителността и човешкия дух.', 
        audioEn: "audio/ORIG/0040_ENG.mp3", 
        audioBg: "audio/ORIG/0040_BUL.mp3" }
];

