const sentences = [
    { title: 1, english: "A Retrieved Reformation", 
        bulgarian: 'Възстановена реформация', 
        audioEn: "audio/ORIG/ENG/0001.mp3", 
        audioBg: "audio/ORIG/BUL/0001.mp3" },
    { english: 'A GUARD CAME to the prison shoe-shop,', 
        bulgarian: 'Надзирателят влезе в обущарницата на затвора,(букв.: "Един надзирател влезе в магазина за обувки на затвора")', 
        audioEn: "audio/ORIG/ENG/0002.mp3", 
        audioBg: "audio/ORIG/BUL/0002.mp3" },
    { english: 'where Jimmy Valentine was assiduously stitching uppers,', 
        bulgarian: 'където Джими Валънтайн прилежно шиеше горни части на обувки', 
        audioEn: "audio/ORIG/ENG/0003.mp3", 
        audioBg: "audio/ORIG/BUL/0003.mp3" },
    { english: 'and escorted him to the front office.', 
        bulgarian: 'и го поведе към канцеларията. (букв.: "и го екскортира до фронт офиса")', 
        audioEn: "audio/ORIG/ENG/0004.mp3", 
        audioBg: "audio/ORIG/BUL/0004.mp3" },
    { english: 'There the warden handed Jimmy his pardon,', 
        bulgarian: 'Там управителят на затвора връчки на Джими заповедта му за помилване,', 
        audioEn: "audio/ORIG/ENG/0005.mp3", 
        audioBg: "audio/ORIG/BUL/0005.mp3" },
    { english: 'which had been signed that morning by the governor.', 
        bulgarian: 'подписана същата сутрин от губернатора. (букв. "която беше подписана в онази сутрин от губернатора)', 
        audioEn: "audio/ORIG/ENG/0006.mp3", 
        audioBg: "audio/ORIG/BUL/0006.mp3" },
    { english: 'Jimmy took it in a tired kind of way.', 
        bulgarian: 'Джими пое документа с уморен вид. (букв. "Джими я пое с уморен вид")', 
        audioEn: "audio/ORIG/ENG/0007.mp3", 
        audioBg: "audio/ORIG/BUL/0007.mp3" },
    { english: 'He had served nearly ten months of a four year sentence.', 
        bulgarian: 'Беше излежал близо десет месеца от четиригодишната си присъда.(букв. "Беше отслужил близо десет месеца от четиригодишнагта си присъда")', 
        audioEn: "audio/ORIG/ENG/0008.mp3", 
        audioBg: "audio/ORIG/BUL/0008.mp3" },
    { english: 'He had expected to stay only about three months,', 
        bulgarian: 'А очакваше да остане в затвора само три месеца', 
        audioEn: "audio/ORIG/ENG/0009.mp3", 
        audioBg: "audio/ORIG/BUL/0009.mp3" },
    { english: 'at the longest.', 
        bulgarian: 'най-много. (букв. "най-дълго")', 
        audioEn: "audio/ORIG/ENG/0010.mp3", 
        audioBg: "audio/ORIG/BUL/0010.mp3" },
];
