const sentences = [
    { title:1, english: "John's Journey", 
        bulgarian: "Пътуването на Джон", 
        audioEn: "audio/A1/0001_ENG.mp3", 
        audioBg: "audio/A1/0001_BUL.mp3" },
    { english: 'John lived in a small village.', 
        bulgarian: 'Джон живееше в малко селце.', 
        audioEn: "audio/A1/0002_ENG.mp3", 
        audioBg: "audio/A1/0002_BUL.mp3" },
    { english: 'He wanted to learn and help others.', 
        bulgarian: 'Той искаше да учи и да помага на другите.', 
        audioEn: "audio/A1/0003_ENG.mp3", 
        audioBg: "audio/A1/0003_BUL.mp3" },
    { english: 'At 16, he went to the city.', 
        bulgarian: 'На 16 години той отиде в града.', 
        audioEn: "audio/A1/0004_ENG.mp3", 
        audioBg: "audio/A1/0004_BUL.mp3" },
    { english: 'He worked hard in a printing shop.', 
        bulgarian: 'Той работеше усърдно в печатница.', 
        audioEn: "audio/A1/0005_ENG.mp3", 
        audioBg: "audio/A1/0005_BUL.mp3" },
    { english: 'He studied at night.', 
        bulgarian: 'Той учеше вечер.', 
        audioEn: "audio/A1/0006_ENG.mp3", 
        audioBg: "audio/A1/0006_BUL.mp3" },
    { english: 'John opened a school for poor children.', 
        bulgarian: 'Джон отвори училище за бедни деца.', 
        audioEn: "audio/A1/0007_ENG.mp3", 
        audioBg: "audio/A1/0007_BUL.mp3" },
    { english: 'The school grew bigger.', 
        bulgarian: 'Училището стана по-голямо.', 
        audioEn: "audio/A1/0008_ENG.mp3", 
        audioBg: "audio/A1/0008_BUL.mp3" },
    { english: 'People loved his school.', 
        bulgarian: 'Хората обичаха неговото училище.', 
        audioEn: "audio/A1/0009_ENG.mp3", 
        audioBg: "audio/A1/0009_BUL.mp3" },
    { english: 'John helped many children.', 
        bulgarian: 'Джон помогна на много деца.', 
        audioEn: "audio/A1/0010_ENG.mp3", 
        audioBg: "audio/A1/0010_BUL.mp3" }
];

