const sentences = [
    { title: 1, english: "John's Legacy of Resilience and Innovation", 
        bulgarian: "Наследството на Джон за устойчивост и иновации", 
        audioEn: "audio/C1/0001_ENG.mp3", 
        audioBg: "audio/C1/0001_BUL.mp3" },
    { english: 'John grew up in a small village where poverty was rampant and opportunities were few.', 
        bulgarian: 'Джон израсна в малко селце, където бедността беше широко разпространена, а възможностите бяха малко.', 
        audioEn: "audio/C1/0002_ENG.mp3", 
        audioBg: "audio/C1/0002_BUL.mp3" },
    { english: 'From a young age, he displayed a remarkable intellect and a thirst for knowledge.', 
        bulgarian: 'Още от малък той показваше изключителен интелект и жажда за знания.', 
        audioEn: "audio/C1/0003_ENG.mp3", 
        audioBg: "audio/C1/0003_BUL.mp3" },
    { english: 'Determined to escape the cycle of poverty, he moved to the city at the age of 16.', 
        bulgarian: 'Решен да избяга от цикъла на бедността, той се премести в града на 16-годишна възраст.', 
        audioEn: "audio/C1/0004_ENG.mp3", 
        audioBg: "audio/C1/0004_BUL.mp3" },
    { english: 'He found work in a printing shop and devoted his evenings to studying.', 
        bulgarian: 'Той намери работа в печатница и посвети вечерите си на учене.', 
        audioEn: "audio/C1/0005_ENG.mp3", 
        audioBg: "audio/C1/0005_BUL.mp3" },
    { english: 'Despite facing numerous challenges, John managed to save enough to open a school for underprivileged children.', 
        bulgarian: 'Въпреки многобройните предизвикателства, Джон успя да спести достатъчно, за да отвори училище за бедни деца.', 
        audioEn: "audio/C1/0006_ENG.mp3", 
        audioBg: "audio/C1/0006_BUL.mp3" },
    { english: 'His innovative teaching methods and dedication quickly gained attention, and the school grew.', 
        bulgarian: 'Неговите иновативни методи на преподаване и отдаденост бързо привлякоха внимание, и училището растеше.', 
        audioEn: "audio/C1/0007_ENG.mp3", 
        audioBg: "audio/C1/0007_BUL.mp3" },
    { english: 'Facing resistance from traditionalists, John remained steadfast in his mission to provide quality education.', 
        bulgarian: 'Срещайки съпротива от традиционалисти, Джон остана непоколебим в мисията си да осигури качествено образование.', 
        audioEn: "audio/C1/0008_ENG.mp3", 
        audioBg: "audio/C1/0008_BUL.mp3" },
    { english: 'A significant donation from a local philanthropist allowed for the school\'s expansion.', 
        bulgarian: 'Значително дарение от местен филантроп позволи разширяването на училището.', 
        audioEn: "audio/C1/0009_ENG.mp3", 
        audioBg: "audio/C1/0009_BUL.mp3" },
    { english: 'John\'s school became a symbol of hope and progress, with many students achieving remarkable success.', 
        bulgarian: 'Училището на Джон се превърна в символ на надежда и прогрес, като много ученици постигнаха забележителни успехи.', 
        audioEn: "audio/C1/0010_ENG.mp3", 
        audioBg: "audio/C1/0010_BUL.mp3" }
];

