const sentences = [
    { title: 1, english: "John's Journey from Poverty to Success", 
        bulgarian: "Пътешествието на Джон от бедността до успеха", 
        audioEn: "audio/B2/0001_ENG.mp3", 
        audioBg: "audio/B2/0001_BUL.mp3" },
    { english: 'John grew up in a poor village where opportunities were scarce.', 
        bulgarian: 'Джон израсна в бедно селце, където възможностите бяха оскъдни.', 
        audioEn: "audio/B2/0002_ENG.mp3", 
        audioBg: "audio/B2/0002_BUL.mp3" },
    { english: 'Despite this, he had a deep love for learning and a desire to help his community.', 
        bulgarian: 'Въпреки това, той имаше дълбока любов към ученето и желание да помогне на своята общност.', 
        audioEn: "audio/B2/0003_ENG.mp3", 
        audioBg: "audio/B2/0003_BUL.mp3" },
    { english: 'At 16, seeking a better future, he moved to the city.', 
        bulgarian: 'На 16 години, търсейки по-добро бъдеще, той се премести в града.', 
        audioEn: "audio/B2/0004_ENG.mp3", 
        audioBg: "audio/B2/0004_BUL.mp3" },
    { english: 'He worked long hours in a printing shop and studied at night.', 
        bulgarian: 'Той работеше дълги часове в печатница и учеше вечер.', 
        audioEn: "audio/B2/0005_ENG.mp3", 
        audioBg: "audio/B2/0005_BUL.mp3" },
    { english: 'John\'s hard work paid off when he opened a school for poor children.', 
        bulgarian: 'Усилията на Джон се отплатиха, когато той отвори училище за бедни деца.', 
        audioEn: "audio/B2/0006_ENG.mp3", 
        audioBg: "audio/B2/0006_BUL.mp3" },
    { english: 'The school grew quickly, thanks to his innovative teaching methods.', 
        bulgarian: 'Училището растеше бързо благодарение на неговите иновативни методи на преподаване.', 
        audioEn: "audio/B2/0007_ENG.mp3", 
        audioBg: "audio/B2/0007_BUL.mp3" },
    { english: 'Despite resistance from traditionalists, John persisted in his mission.', 
        bulgarian: 'Въпреки съпротивата от страна на традиционалистите, Джон продължи с мисията си.', 
        audioEn: "audio/B2/0008_ENG.mp3", 
        audioBg: "audio/B2/0008_BUL.mp3" },
    { english: 'A local philanthropist\'s donation helped the school expand significantly.', 
        bulgarian: 'Дарение от местен филантроп помогна на училището да се разшири значително.', 
        audioEn: "audio/B2/0009_ENG.mp3", 
        audioBg: "audio/B2/0009_BUL.mp3" },
    { english: 'John\'s school became a beacon of hope, inspiring students to achieve great success.', 
        bulgarian: 'Училището на Джон стана маяк на надежда, вдъхновявайки учениците да постигнат големи успехи.', 
        audioEn: "audio/B2/0010_ENG.mp3", 
        audioBg: "audio/B2/0010_BUL.mp3" }
];

