const sentences = [
    { title: 1, english: "John's Struggles and Triumph", 
        bulgarian: "Борбите и триумфът на Джон", 
        audioEn: "audio/B1/0001_ENG.mp3", 
        audioBg: "audio/B1/0001_BUL.mp3" },
    { english: 'John grew up in a poor village where he had little support.', 
        bulgarian: 'Джон израсна в бедно селце, където имаше малко подкрепа.', 
        audioEn: "audio/B1/0002_ENG.mp3", 
        audioBg: "audio/B1/0002_BUL.mp3" },
    { english: 'He loved to learn and wanted to help his community.', 
        bulgarian: 'Той обичаше да учи и искаше да помогне на своята общност.', 
        audioEn: "audio/B1/0003_ENG.mp3", 
        audioBg: "audio/B1/0003_BUL.mp3" },
    { english: 'At 16, seeking a better future, he moved to the city.', 
        bulgarian: 'На 16 години, търсейки по-добро бъдеще, той се премести в града.', 
        audioEn: "audio/B1/0004_ENG.mp3", 
        audioBg: "audio/B1/0004_BUL.mp3" },
    { english: 'He worked long hours in a printing shop and studied at night.', 
        bulgarian: 'Той работеше дълги часове в печатница и учеше вечер.', 
        audioEn: "audio/B1/0005_ENG.mp3", 
        audioBg: "audio/B1/0005_BUL.mp3" },
    { english: 'Despite many challenges, he managed to open a school for poor children.', 
        bulgarian: 'Въпреки многото предизвикателства, той успя да отвори училище за бедни деца.', 
        audioEn: "audio/B1/0006_ENG.mp3", 
        audioBg: "audio/B1/0006_BUL.mp3" },
    { english: 'The school grew, and his innovative teaching methods gained attention.', 
        bulgarian: 'Училището растеше, а неговите иновативни методи на преподаване привлякоха внимание.', 
        audioEn: "audio/B1/0007_ENG.mp3", 
        audioBg: "audio/B1/0007_BUL.mp3" },
    { english: 'John faced resistance from traditionalists but persevered.', 
        bulgarian: 'Джон се сблъска със съпротива от традиционалисти, но продължи да се бори.', 
        audioEn: "audio/B1/0008_ENG.mp3", 
        audioBg: "audio/B1/0008_BUL.mp3" },
    { english: 'A local philanthropist helped fund the school, allowing it to expand.', 
        bulgarian: 'Местен филантроп помогна с финансиране на училището, което позволи то да се разшири.', 
        audioEn: "audio/B1/0009_ENG.mp3", 
        audioBg: "audio/B1/0009_BUL.mp3" },
    { english: 'John\'s school became a beacon of hope, and his students achieved great success.', 
        bulgarian: 'Училището на Джон стана маяк на надежда, а неговите ученици постигнаха големи успехи.', 
        audioEn: "audio/B1/0010_ENG.mp3", 
        audioBg: "audio/B1/0010_BUL.mp3" }
];

