const sentences = [
    { title:1, english: "John's Success", 
        bulgarian: "Успехът на Джон", 
        audioEn: "audio/A2/0001_ENG.mp3", 
        audioBg: "audio/A2/0001_BUL.mp3" },
    { english: 'John grew up in a poor village.', 
        bulgarian: 'Джон израсна в бедно селце.', 
        audioEn: "audio/A2/0002_ENG.mp3", 
        audioBg: "audio/A2/0002_BUL.mp3" },
    { english: 'He loved to learn and wanted to help others.', 
        bulgarian: 'Той обичаше да учи и искаше да помага на другите.', 
        audioEn: "audio/A2/0003_ENG.mp3", 
        audioBg: "audio/A2/0003_BUL.mp3" },
    { english: 'At 16, he moved to the city for a better life.', 
        bulgarian: 'На 16 години той се премести в града за по-добър живот.', 
        audioEn: "audio/A2/0004_ENG.mp3", 
        audioBg: "audio/A2/0004_BUL.mp3" },
    { english: 'He worked in a printing shop and studied at night.', 
        bulgarian: 'Той работеше в печатница и учеше вечер.', 
        audioEn: "audio/A2/0005_ENG.mp3", 
        audioBg: "audio/A2/0005_BUL.mp3" },
    { english: 'John opened a school for poor children.', 
        bulgarian: 'Джон отвори училище за бедни деца.', 
        audioEn: "audio/A2/0006_ENG.mp3", 
        audioBg: "audio/A2/0006_BUL.mp3" },
    { english: 'The school grew and became popular.', 
        bulgarian: 'Училището растеше и стана популярно.', 
        audioEn: "audio/A2/0007_ENG.mp3", 
        audioBg: "audio/A2/0007_BUL.mp3" },
    { english: 'He used new teaching methods.', 
        bulgarian: 'Той използваше нови методи на преподаване.', 
        audioEn: "audio/A2/0008_ENG.mp3", 
        audioBg: "audio/A2/0008_BUL.mp3" },
    { english: 'John helped many children to learn and succeed.', 
        bulgarian: 'Джон помогна на много деца да учат и да успеят.', 
        audioEn: "audio/A2/0009_ENG.mp3", 
        audioBg: "audio/A2/0009_BUL.mp3" },
    { english: 'His school became famous, and he inspired many people.', 
        bulgarian: 'Неговото училище стана известно и той вдъхнови много хора.', 
        audioEn: "audio/A2/0010_ENG.mp3", 
        audioBg: "audio/A2/0010_BUL.mp3" }
];

